#dev   第二次修改
server:
  port: 7003

eureka:
  instance:
    #eureka服务端的实例名字
    hostname: eureka7003.com
  client:
    #表识不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #如果是7001的eureka，那么应该填7002的地址
      #如果有3个集群，分别是A、B、C，那么现在是A，下面就要填B、C的地址，多个地址中间用‘,’隔开即可
      defaultZone: http://eureka7003.com:7003/eureka/
  #关闭自我保护机制，保证不可用服务被及时踢除
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
